from local_secret import API_SERVICE_URL, API_USERNAME, API_ADMIN_PASSWORD, SENSOR_USERNAME, SENSOR_PASSWORD

# api
API_SERVICE_URL = API_SERVICE_URL
API_USERNAME = API_USERNAME
API_ADMIN_PASSWORD = API_ADMIN_PASSWORD

# malawi sensor satellite data
SENSOR_USERNAME = SENSOR_USERNAME
SENSOR_PASSWORD = SENSOR_PASSWORD
