from enum import Enum


class PrecipitationSum(Enum):
    UPPER_VALUE_12HR_EVENT = 100
    UPPER_VALUE_24HR_EVENT = 200
    UPPER_VALUE_48HR_EVENT = 200
    UPPER_VALUE_4HR_EVENT = 70
    UPPER_VALUE_2HR_EVENT = 70
    UPPER_VALUE_1HR_EVENT = 60
